#' Bodyids for neuron classes
#'
#' Bodyids for neuron classes. Hard saved equivalent for \code{\link{class2ids}}.
#' However, you should use \code{\link{class2ids}} for the most up-to-date information.
#'
#' @details neuPrint bodyids for neurons that the FlyConnectome groups at the University of Cambridge, dept. Zoology,
#' have determined to fall into different classes.
#'
#' @seealso \code{\link{class2ids}}
#' @examples
#' \donttest{
#' head(rn.ids)
#' }
#' @name classed.ids
#' @rdname classed.ids
"rn.ids"

#' The hemibrain mesh
#'
#' A 3D mesh of the hemibrain volume as a \code{\link[nat]{hxsurf}} object.
#' Created by Philipp Schlegel from the union of individual ROIs in FlyEM's
#' hemibrain project. Mesh available both in raw voxels and in microns.
#'
#' @details note that hemibrain coordinate system does not have the
#'   anterior-posterior axis aligned with the Z axis.
#'
#' @source \url{https://neuprint.janelia.org/}
#' @seealso \code{\link{hemibrain_roi_meshes}}
#' @examples
#' \donttest{
#' library(nat)
#' \dontrun{
#' plot3d(hemibrain.surf, alpha=.3, col='grey')
#'
#' # can also convert to rgl mesh3d object for more control
#' hemibrain <- as.mesh3d(hemibrain.surf)
#' rgl::wire3d(hemibrain)
#' rgl::shade3d(hemibrain, alpha=.3)
#' rgl::shade3d(hemibrain, alpha=.3, col='grey')
#' }
#' }
#' @name hemibrain.surf
#' @rdname hemibrain.surf
"hemibrain.surf"
#' @rdname hemibrain.surf
"hemibrain_microns.surf"

#' Meshes for antennal love glomeruli
#'
#' 3D meshes of 51 olfactory + 7 thermosensory antennal lobe glomeruli for the the hemibrain volume.
#' They are represented as a \code{\link[nat]{hxsurf}} object, in which 58 'regions' are defined,
#' one for each glomerulus. Meshes available both in raw voxels and in microns.
#'
#' @details note that hemibrain coordinate system does not have the
#'   anterior-posterior axis aligned with the Z axis.
#'
#' @source \url{https://neuprint.janelia.org/}
#' @seealso \code{\link{hemibrain_roi_meshes}}
#' @examples
#' \donttest{
#' library(nat)
#' \dontrun{
#' plot3d(hemibrain_al.surf, alpha=.3)
#'
#' # can also plot single glomeruli
#' plot3d(subset(hemibrain_al.surf,"DM1"))
#'
#' }
#' }
#' @name hemibrain_al.surf
#' @rdname hemibrain_al.surf
"hemibrain_al.surf"
#' @rdname hemibrain_al.surf
"hemibrain_al_microns.surf"

#' Axon-dendrite split points calculated for all hemibrain neurons
#'
#' Axon-dendrite split points calculated for the whole hemibrain dataset,
#' hemibrain:v1.0.1, using a variety of parameters. The file used to generate this can be found in this
#' package, as \code{data-raw/hemibrain_split_all_neurons.R}. The arguments given
#' to \code{\link{flow_centrality}} are in the name of the data frame.
#' Note that, because the proportion of recovered synapses is unevenly distributed across brain
#' regions, after compartment detection, sometimes the dendrite was chosen as the neurite
#' closest to a neuron's primary branch point (data frames with 'distance' in their name), see reference.
#'
#' @references Bates, A. S., P. Schlegel, R. J. V. Roberts, N. Drummond, I. F.
#'   M. Tamimi, R. Turnbull, X. Zhao, et al. 2020. “Complete Connectomic
#'   Reconstruction of Olfactory Projection Neurons in the Fly Brain.” bioRxiv.
#'   https://doi.org/10.1101/2020.01.19.911453.
#'
#' @source \url{https://www.biorxiv.org/content/10.1101/2020.01.19.911453v1}
#' @seealso \code{\link{hemibrain_flow_centrality}},
#'   \code{\link{flow_centrality}},
#'   \code{\link{hemibrain_use_splitpoints}}
#' @examples
#' \donttest{
#' head(hemibrain_splitpoints_polypre_centrifugal_distance)
#' \dontrun{
#' View(hemibrain_splitpoints_polypre_centrifugal_distance)
#' }
#' }
#' @name hemibrain_precomputed_splitpoints
#' @rdname hemibrain_precomputed_splitpoints
"hemibrain_all_splitpoints"
#' @rdname hemibrain_precomputed_splitpoints
"hemibrain_splitpoints_polypre_centrifugal_distance"
#' @rdname hemibrain_precomputed_splitpoints
"hemibrain_splitpoints_pre_centrifugal_distance"
#' @rdname hemibrain_precomputed_splitpoints
"hemibrain_splitpoints_polypre_centrifugal_synapses"

#' Neuron metrics for all neurons in the hemibrain dataset
#'
#' This \code{data.frame} give metrics for neurons, such as cable lengths and pre/post synapse numbers and densities,
#' broken down by putative compartment. E.g. axons versus dendrite. This has been calculated for neurons across the hemibrain dataset,
#' hemibrain:v1.0.1. The file used to generate this can be found in this package,
#' as \code{data-raw/hemibrain_split_all_neurons.R}. Neurons were split as described by \code{\link{hemibrain_precomputed_splitpoints}}. Note
#' that the first two columns, \code{pre} and \code{post} are generated by neuPrint. They differ from similar numbers in other columns of
#' this \code{data.frame} because 'pre' is later given as the numbers of outgoing connections (not presynapses) and some erroneous pre/post synapses will
#' have been removed by \code{\link{hemibrain_skeleton_check}}. Overlap locality is calculated as the 'overlap score' (Frechter et al. 2019, eLife) between
#' a neuron's axon and dendrite.
#'
#' @references Frechter, Shahar, Alexander Shakeel Bates, Sina Tootoonian, Michael-John Dolan, James D. Manton, Arian Rokkum Jamasb, Johannes Kohl, Davi Bock, and Gregory Sxe Jefferis. 2019.
#' “Functional and Anatomical Specificity in a Higher Olfactory Centre.” eLife 8 (May). https://doi.org/10.7554/eLife.44590.
#'
#' @source \url{https://elifesciences.org/articles/44590}
#' @seealso \code{\link{hemibrain_flow_centrality}}, \code{\link{hemibrain_precomputed_splitpoints}}, \code{\link{axonic_cable}}, \code{\link{dendritic_cable}}
#' @examples
#' \donttest{
#' head(hemibrain_metrics)
#' hist(hemibrain_metrics$overlap_locality,breaks = 1000)
#' }
#' @name hemibrain_metrics
#' @rdname hemibrain_metrics
"hemibrain_metrics"
#' @rdname hemibrain_metrics
"hemibrain_metrics_polypre_centrifugal_distance"
#' @rdname hemibrain_metrics
"hemibrain_all_neurons_metrics_polypre_centrifugal_synapses"

